### ISSUE TITLE
Host website in github pages

### ISSUE THREAD

**Issue by JoseRoman** [Ernie3/khs-minithon#16]
@Ernie3 It won't let me do it, because I'm not the owner of the repo. You should be able to follow the instructions in https://pages.github.com/ and get it to work.

**Comment by Ernie3** [comment]
Sweet. I will take a look at this when I get a change tonight or this weekend.

**Comment by JoseRoman** [comment]
@Ernie3 I already did this. 

![image](https://cloud.githubusercontent.com/assets/4240075/10125174/c381b486-651f-11e5-9037-65edf55f8746.png)

**Comment by Ernie3** [comment]
I have other things to do not just this!!!!! Thanks man lol

**Comment by JoseRoman** [comment]
@Ernie3  
![image](https://cloud.githubusercontent.com/assets/4240075/10125190/06f25748-6520-11e5-9cc9-5a639b9014bb.png)
